import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

'''
diq3d: plots $ vs API, individually by race. Takes in data.csv, which was generated by diq3c.py. Outputs files used by 3e and then 3f.

Racial classifications
aa: african american
ai: american indian
as: asian
fi: filipino
hi: hispanic
pi: pacific islander
wh: white
mr: multiracial
sd: socioeconomically disadvantaged
el: english learner
di: disabilities
'''

data = pd.read_csv('data.csv', index_col=0)

classes = {'all': 'total', 'aa': 'African American', 'ai': 'American Indian', 'as': 'Asian', 'fi': 'Filipino', 'hi': 'Hispanic', 'pi': 'Pacific Islander', 'wh': 'White', 'mr': 'Multiracial', 'sd': 'Socioeconomically Disadvantaged', 'el': 'English Learner', 'di': 'Disabled'}
classesM = {'all': 0.000166546, 'aa': 0.0001096435, 'ai': 0.0001483556, 'as': 0.0001531716, 'fi': 0.0000375384, 'hi': 0.0000918279, 'pi': 0.0000238732, 'wh': 0.00015981, 'mr': 0.000156034, 'sd': 0.0000872444, 'el': 0.000121062, 'di': 0.000158461} # from excel
classesB = {'all': 724.3871119, 'aa': 705.9881, 'ai': 706.551, 'as': 817.405, 'fi': 858.4629906, 'hi': 726.9845, 'pi': 747.6216204, 'wh': 772.3305834, 'mr': 786.7908795, 'sd': 724.1532489, 'el': 694.9082121, 'di': 575.8940991} # from excel

for key in classes:
    if key == 'all':
        searchcol = 'avg_w'
        zaout = 'zindex-api.csv'
        zmout = 'zindex-api-sorted.csv'
        figout = 'zindex-api.png'
        num11 = 'num11'
        num12 = 'num12'
        num13 = 'num13'
        numavg = 'num_avg'
    else:
        searchcol = key + '_avg_w'
        zaout = 'zindex-api-' + key + '.csv'
        zmout = 'zindex-api-' + key + '-sorted.csv'
        figout = 'zindex-api-' + key + '.png'
        num11 = key + '_num11'
        num12 = key + '_num12'
        num13 = key + '_num13'
        numavg = key + '_num_avg'
    w = data.loc[:,['Zip', 'zindex', searchcol]]
    w2 = data.loc[:,[num11, num12, num13]]
    w = w.dropna(how='any')
    w = pd.merge(w, w2, left_index=True, right_index=True, how='left')
    av = w[[num11, num12, num13]].mean(axis=1)
    w = pd.concat([w,av],axis=1,join='inner')
    w = w.rename(columns={0: numavg})
 
    wgroup = w.groupby('Zip')   

    za = wgroup[['zindex',searchcol]].mean()
    zn = wgroup[[num11,num12,num13,numavg]].sum()
    z = pd.concat([za,zn],axis=1,join='outer')
    z.to_csv(zaout)
    zmod = z[z.zindex < 1000000]
    zmod = zmod.sort_values(searchcol, axis=0, ascending=False, inplace=False)
    zmod.to_csv(zmout)
    

    f, (ax1, ax2) = plt.subplots(1, 2, sharey=True, figsize=(18,6))
    ax1.scatter(z.zindex,z.ix[:,1], color='red', marker='^', alpha=0.2)
    ax2.scatter(zmod.zindex,zmod.ix[:,1], color='red', marker='^', alpha=0.3)
    ax1.set_title("Zillow Home Value Index versus school %s API score at each CA ZIP" % classes[key], loc='left')
    ax1.set_xlabel("Zillow Home Value Index ($)")
    ax2.set_xlabel("Zillow Home Value Index ($)")
    ax1.set_ylabel("Average school %s API score" % classes[key])
    ax1.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    ax2.ticklabel_format(style='sci', axis='x', scilimits=(0,0))

    
    zlinex = np.linspace(0,1000000)
    m = classesM[key] 
    b = classesB[key]
    zliney = zlinex * m + b
    ax2.plot(zlinex, zliney)
    
    f.savefig(figout)
