import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

'''
diq3f: plots API deviation vs public school attendance. Takes in totalschoolsbyzip.csv, which was generated by diq3e.py
'''

z=pd.read_csv('totalschoolsbyzip.csv', index_col=0)
z['wp'] = z['percent public']*z['Population']
z['wa'] = z['API - expected']*z['Population']
zgroup = z.groupby('SCF')
pop = zgroup.sum()[['Population','wp','wa']]
pop['percent public'] = pop['wp']/pop['Population']
pop['API - expected'] = pop['wa']/pop['Population']

pop.to_csv('SCF.csv')
'''
zmod = z[z.zindex < 1000000]
f, (ax1, ax2) = plt.subplots(1, 2, sharey=True, figsize=(18,6))
plt.xlim(0.5,1)
#ax2.set_xscale('log')
ax1.scatter(z['percent public'],z['API - expected'], color='red', marker='^', alpha=0.2)
ax2.scatter(zmod['percent public'],zmod['API - expected'], color='red', marker='^', alpha=0.3)
ax1.set_title("API deviation from expected value versus public school percentage", loc='left')
ax1.set_xlabel("Percent of students in public schools")
ax2.set_xlabel("Percent of students in public schools in zip codes with Zindex < $1 million")
ax1.set_ylabel("Actual API minus expected API")
ax1.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
ax2.ticklabel_format(style='sci', axis='x', scilimits=(0,0))

'''
'''
zlinex = np.linspace(0,1000000)
m = 0.000166546 # from excel
b = 724.3871119
zliney = zlinex * m + b
ax2.plot(zlinex, zliney)
'''
'''
f.savefig("apidev.png")
'''
#g, (ax3, ax4) = plt.subplots(1, 2, sharey=True, figsize=(18,6))
plt.scatter(pop['percent public'],pop['API - expected'], color='red', marker='^', alpha=0.5)
#ax4.scatter(tmod.zindex,tmod.avg_w, color='red', marker='^', alpha=0.3)
plt.title("API deviation from expected value versus public school percentage", loc='left')
plt.xlabel("Percent of students in public schools")
#ax4.set_xlabel("Zillow Home Value Index ($)")
plt.ylabel("Actual API minus expected API")
#plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
#ax4.ticklabel_format(style='sci', axis='x', scilimits=(0,0))

tlinex = np.linspace(0.6,1)
tm = 250.1516317 # from excel
tb = -232.4247356
tliney = tlinex * tm + tb
plt.plot(tlinex, tliney)

'''

df = pop[['percent public','API - expected']]

df.plot.scatter(x='percent public', y='API - expected');
'''
plt.savefig("apidev-scf.png")