import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

'''
diq3g: plots $ vs API, color-coded by race. Takes in data.csv, which was generated by diq3c.py

Racial classifications
aa: african american
ai: american indian
as: asian
fi: filipino
hi: hispanic
pi: pacific islander
wh: white
mr: multiracial
sd: socioeconomically disadvantaged
el: english learner
di: disabilities
'''

data = pd.read_csv('data.csv', index_col=0)

classes = {'as': 'Asian', 'wh': 'White', 'hi': 'Hispanic', 'aa': 'Black'}
classesM = {'as': 0.0001531716, 'wh': 0.00015981, 'hi': 0.0000918279, 'aa': 0.0001096435} # from excel
classesB = {'as': 817.405, 'wh': 772.3305834, 'hi': 726.9845, 'aa': 705.9881} # from excel
classesC = {'as': 'orange', 'wh': 'blue', 'hi': 'green', 'aa': 'black'}

f, (ax1, ax2) = plt.subplots(1, 2, sharey=True, figsize=(18,6))
for key in classes:
    if key == 'all':
        searchcol = 'avg_w'
        zaout = 'zindex-api.csv'
        zmout = 'zindex-api-sorted.csv'
        figout = 'zindex-api.png'
        num11 = 'num11'
        num12 = 'num12'
        num13 = 'num13'
        numavg = 'num_avg'
    else:
        searchcol = key + '_avg_w'
        zaout = 'zindex-api-' + key + '.csv'
        zmout = 'zindex-api-' + key + '-sorted.csv'
        figout = 'zindex-api-' + key + '.png'
        num11 = key + '_num11'
        num12 = key + '_num12'
        num13 = key + '_num13'
        numavg = key + '_num_avg'
    w = data.loc[:,['Zip', 'zindex', searchcol]]
    w2 = data.loc[:,[num11, num12, num13]]
    w = w.dropna(how='any')
    w = pd.merge(w, w2, left_index=True, right_index=True, how='left')
    av = w[[num11, num12, num13]].mean(axis=1)
    w = pd.concat([w,av],axis=1,join='inner')
    w = w.rename(columns={0: numavg})
 
    wgroup = w.groupby('Zip')   

    za = wgroup[['zindex',searchcol]].mean()
    zn = wgroup[[num11,num12,num13,numavg]].sum()
    z = pd.concat([za,zn],axis=1,join='outer')
    z.to_csv(zaout)
    zmod = z[z.zindex < 1000000]
    zmod = zmod.sort_values(searchcol, axis=0, ascending=False, inplace=False)
    zmod.to_csv(zmout)
    

    
    ax1.scatter(z.zindex,z.ix[:,1], color=classesC[key], marker='^', alpha=0.3, label=classes[key])
    ax2.scatter(zmod.zindex,zmod.ix[:,1], color=classesC[key], marker='^', alpha=0.4, label=classes[key])
    ax1.set_xlabel("Zillow Home Value Index ($)")
    ax2.set_xlabel("Zillow Home Value Index ($)")
    ax1.set_ylabel("Average school API score")
    ax1.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    ax2.ticklabel_format(style='sci', axis='x', scilimits=(0,0))

    
    zlinex = np.linspace(0,1000000)
    m = classesM[key] 
    b = classesB[key]
    zliney = zlinex * m + b
    ax2.plot(zlinex, zliney, color=classesC[key])

#ax1.legend()
ax1.set_title("Zillow Home Value Index versus school API score at each CA ZIP, breakdown by race", loc='left')
ax2.legend(loc=4)    
f.savefig('zindex-api-combined.png')
