import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

'''
Takes in private school data taken from the California DoE. Takes in census data as well. Takes in zindex-api.csv generated by diq3d.py. Combines them to make totalschoolsbyzip.csv which is used in diq3f.py
'''

private11 = pd.read_csv('privateschools1011.csv',header=3)
redp11 = private11[['Zip','Total Enrollment']]
redp11 = redp11.rename(columns={'Total Enrollment': 'Total Enrollment 11'})
redp11['Zip']=redp11['Zip'].apply(lambda x: int(x.split('-')[0]))
penroll11 = redp11.groupby('Zip').sum()

private12 = pd.read_csv('privateschools1112.csv',header=3)
redp12 = private12[['Zip','Total Enrollment']]
redp12 = redp12.rename(columns={'Total Enrollment': 'Total Enrollment 12'})
penroll12 = redp12.groupby('Zip').sum()

private13 = pd.read_csv('privateschools1213.csv',header=3)
redp13 = private13[['Zip','Total Enrollment']]
redp13 = redp13.rename(columns={'Total Enrollment': 'Total Enrollment 13'})
penroll13 = redp13.groupby('Zip').sum()

penroll = pd.concat([penroll11,penroll12,penroll13],axis=1,join='outer')
av = penroll[['Total Enrollment 11', 'Total Enrollment 12', 'Total Enrollment 13']].mean(axis=1)
penroll = pd.concat([penroll,av],axis=1,join='outer')
penroll = penroll.rename(columns={0: 'private average'})

penroll.to_csv('privateschoolbyzip.csv')

pubschools = pd.read_csv('zindex-api.csv', index_col=0)

total = pd.merge(penroll,pubschools,right_index=True,left_index=True,how='right')
total['private average'] = total['private average'].fillna(value=0)
ts = total['private average'] + total['num_avg']
pp = total['num_avg'] / ts
m = 0.000166546 # from excel
b = 724.3871119 # from excel
ea = total['zindex']*m+b
ea = ea.rename('expected api')
def f(x):
    if x > 1000:
        return 1000
    else:
        return x
ea = ea.apply(f)
ae = total['avg_w'] - ea

total['SCF'] = total.index/100
total['SCF'] = total['SCF'].apply(lambda x: int(x))

census = pd.read_csv('2010Census.csv', index_col=0)
census = census[census.index >= 90000]
census = census[census.index < 96200]

#total = pd.concat([z, scf, census], axis=1, join='inner')
total = pd.concat([total,ts,pp,ea,ae], axis=1, join='outer')
total = pd.concat([total,census], axis = 1, join='inner')
total = total.rename(columns={0: 'total students', 1:'percent public', 2:'API - expected', 3: 'SCF'})

#z = z.rename(columns={0: 'SCF'})

total.to_csv('totalschoolsbyzip.csv')
